apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "emqx.fullname" . }}-env
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "emqx.name" . }}
    helm.sh/chart: {{ include "emqx.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  {{- range $index, $value := .Values.emqxConfig}}
      {{$index}}: {{ $value }}
    {{- end}}